import { GAME_CONSTANTS } from '../../shared/constants.js'
import { createInitialGameState } from './gameLogic.js'

export function generateRoomCode() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  let code = ''
  for (let i = 0; i < 6; i++) {
    code += chars[Math.floor(Math.random() * chars.length)]
  }
  return code
}

export function createRoom(hostId, hostName, settings = { timerSeconds: 0 }) {
  return {
    id: generateRoomCode(),
    hostId,
    players: [{ id: hostId, name: hostName }],
    settings,
    status: 'waiting',
    gameState: null,
  }
}

export function addPlayerToRoom(room, playerId, playerName) {
  if (room.status !== 'waiting') {
    return { success: false, error: 'Game already started' }
  }
  if (room.players.length >= GAME_CONSTANTS.MAX_PLAYERS) {
    return { success: false, error: 'Room is full' }
  }
  const updatedRoom = {
    ...room,
    players: [...room.players, { id: playerId, name: playerName }],
  }
  return { success: true, room: updatedRoom }
}

export function removePlayerFromRoom(room, playerId) {
  const players = room.players.filter(p => p.id !== playerId)
  let hostId = room.hostId
  if (room.hostId === playerId && players.length > 0) {
    hostId = players[0].id
  }
  return { ...room, players, hostId }
}

export function startGame(room) {
  const gameState = createInitialGameState(room.players, room.settings)
  return { ...room, status: 'playing', gameState }
}

/* TESTS
 * generateRoomCode:
 *   - Returns a string of exactly 6 characters
 *   - Contains only uppercase letters and digits
 *   - Repeated calls produce different codes (probabilistically)
 *
 * createRoom:
 *   - Returns room with hostId and host as first player
 *   - status is 'waiting', gameState is null
 *   - settings are stored on the room
 *   - id is a 6-char code generated by generateRoomCode
 *   - Default settings apply when none provided
 *
 * addPlayerToRoom:
 *   - Returns { success: true, room } with player appended to players list
 *   - Returns error if room.status is not 'waiting'
 *   - Returns error if players.length is already MAX_PLAYERS (4)
 *   - Does not mutate the original room object
 *
 * removePlayerFromRoom:
 *   - Removes the specified player from players array
 *   - If removed player was host and others remain, hostId changes to first remaining player
 *   - If removed player was not host, hostId stays the same
 *   - If last player is removed, players array is empty
 *   - Does not mutate the original room object
 *
 * startGame:
 *   - Sets room.status to 'playing'
 *   - Populates room.gameState via createInitialGameState
 *   - gameState contains dealt hands for all room.players
 *   - Does not mutate the original room object
 */
